### ISSUE TITLE
Write unit tests for `io._pyspark` module

### ISSUE THREAD

**Issue by EFT-Defra** [Defra-Data-Science-Centre-of-Excellence/esa_geo_utils#10]
For:
- [ ] `_add_missing_fields`
- [x] `_add_vsi_prefix`
- [ ] `_coerce_columns_to_schema`
- [ ] `_coerce_types_to_schema`
- [x] `_create_schema`
- [ ] `_create_paths_df`
- [ ] `_drop_additional_columns`
- [x] `_get_feature_count`
- [x] `_get_feature_schema`
- [x] `_get_features`
- [ ] `_get_fields`
- [ ] `_get_field_names_and_columns_names`
- [x] `_get_geometry`
- [x] `_get_layer`
- [x] `_get_layer_name`
- [x] `_get_layer_names`
- [ ] `_get_missing_fields_and_additional_columns`
- [x] `_get_paths`
- [x] `_get_properties`
- [x] `_get_property_names`
- [x] `_get_property_types`
- [ ] `_null_data_frame_from_schema`
- [ ] `_parallel_read_generator`
- [ ] `_spark_df_from_vector_files`
- [ ] `_vector_file_to_pdf`
